
### Create a task
POST http://localhost:4004/odata/v4/task/Tasks
Content-Type: application/json

{
  "title": "task2 - user3",
  "description": "matters a bit",
  "priority": "medium",
  "limitDate": "2025-11-05T00:00:00Z",
  "username": "user3"
  
}


### updade task
PUT http://localhost:4004/odata/v4/task/Tasks('f545d055-6a4a-497f-bc3b-ab29c7473f30')
Content-Type: application/json

{
  "status":"done"
}

### Create a user
POST http://localhost:4004/odata/v4/task/Users
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@email.com"
}

