
### Create a task
POST http://localhost:4004/odata/v4/task/Tasks
Content-Type: application/json

{
  "title": "task999 - user1",
  "description": "matters a bit",
  "priority": "high",
  "limitDate": "2025-11-05T00:00:00Z",
  "username": "user1"
  
}


### updade task
PUT http://localhost:4004/odata/v4/task/Tasks('5b110b09-e565-4736-a484-0e54bddebdab')
Content-Type: application/json

{
  "status":"done"
}

### Create a user
POST http://localhost:4004/odata/v4/task/Users
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@email.com"
}

